(* This file was generated by lv6 version v6.104.0. *)
(*  lv6 -ec -node ciruitg1 -o Lustre/circuitg1.ec Lustre/circuitg1.lus *)
(* on lilian-desktop the 18/11/2021 at 11:04:30 *)

node ciruitg1(a:bool; b:bool; c:bool; d:bool) 
returns (s:bool);
var
   __split_1_1:bool;
   __split_2_1:bool;
   _split_3:bool;
let
   s = (_split_3) and (d);
   __split_2_1 = not (c);
   __split_1_1 = (a) and (b);
   _split_3 = (__split_1_1) or (__split_2_1);
tel
-- end of node circuitg1__ciruitg1
