(* This file was generated by lv6 version v6.104.0. *)
(*  lv6 -ec -node ciruitg3 -o Lustre/circuitg3.ec Lustre/circuitg3.lus *)
(* on lilian-desktop the 18/11/2021 at 11:24:53 *)

node ciruitg3(a:bool; b:bool; s:bool) 
returns (f:bool);
var
   __split_1_1:bool;
   __split_2_1:bool;
   __split_3_1:bool;
let
   __split_3_1 = (__split_2_1) and (b);
   __split_2_1 = not (s);
   __split_1_1 = (s) and (a);
   f = (__split_1_1) or (__split_3_1);
tel
-- end of node circuitg3__ciruitg3
