(* This file was generated by lv6 version v6.104.0. *)
(*  lv6 -ec -node cir1 -o TP2/circuit1.ec TP2/circuit1.lus *)
(* on lilian-desktop the 23/11/2021 at 10:14:46 *)

node cir1(a:bool; b:bool) 
returns (c:bool);
var
   _split_1:bool;
let
   c = (a) and (_split_1);
   _split_1 = not (b);
tel
-- end of node circuit1__cir1
